from pyspark.sql import SparkSession
# Only include the necessary functions for native rounding and windowing
from pyspark.sql.functions import window, max, col, when, date_format, rank, round
from pyspark.sql.window import Window 

# --- Alerting Thresholds for Team 27 ---
NET_IN_THRESHOLD = 4617.8
DISK_IO_THRESHOLD = 3995.9

# 1. Create a SparkSession
spark = SparkSession.builder.appName("Network_Disk_Analysis_NativeRound").getOrCreate()

# 2. Read the intermediate CSV files generated by the consumer
net_df = spark.read.csv("net_data.csv", header=True, inferSchema=True)
disk_df = spark.read.csv("disk_data.csv", header=True, inferSchema=True)

# 3. Join the data and rename the timestamp column
metrics_df = net_df.join(disk_df, ["ts", "server_id"]) \
    .withColumnRenamed("ts", "timestamp") \
    .withColumn("timestamp", col("timestamp").cast("timestamp")) 

# 4. Apply a sliding window and find the MAX value in each window
windowed_agg_df = metrics_df.groupBy(
    col("server_id"),
    window(col("timestamp"), windowDuration="30 seconds", slideDuration="10 seconds").alias("window")
).agg(
    max("net_in").alias("max_net_in_unrounded"),
    max("disk_io").alias("max_disk_io_unrounded")
)

# -----------------------------------------------------------------------------------
# 5. FIX: Filter Incomplete/Misaligned Initial Windows (Removes extra rows)
# -----------------------------------------------------------------------------------
# Define a window specification to partition by server_id and order by window start time
window_spec = Window.partitionBy("server_id").orderBy(col("window.start"))

# Add a rank column to identify the order of windows per server
ranked_df = windowed_agg_df.withColumn(
    "window_rank", 
    rank().over(window_spec)
)

# Filter out the first two windows (rank 1 and rank 2) for each server.
df_filtered = ranked_df.filter(col("window_rank") > 2).drop("window_rank")
print("\n✅ Row count fix maintained: Filtered out initial misaligned windows.")


# 6. Apply the specific alerting logic for Network and Disk (Uses UNROUNDED values)
alerts_df = df_filtered.withColumn("alert",
    when((col("max_net_in_unrounded") > NET_IN_THRESHOLD) & (col("max_disk_io_unrounded") > DISK_IO_THRESHOLD), 
         "Network flood + Disk thrash suspected")
    .when((col("max_net_in_unrounded") > NET_IN_THRESHOLD), "Possible DDoS")
    .when((col("max_disk_io_unrounded") > DISK_IO_THRESHOLD), "Disk thrash suspected")
    .otherwise("")
)

# -----------------------------------------------------------------------------------
# 7. FIX: Use Native PySpark round() function for display
# -----------------------------------------------------------------------------------

# Format the output to match the required schema
final_df = alerts_df.select(
    col("server_id"),
    col("window.start").cast("timestamp").alias("window_start"),
    col("window.end").cast("timestamp").alias("window_end"),
    
    # APPLY NATIVE ROUND: Uses standard round-half-up (e.g., 5.145 -> 5.15)
    round(col("max_net_in_unrounded"), 2).alias("max_net_in"),
    round(col("max_disk_io_unrounded"), 2).alias("max_disk_io"),
    
    col("alert")
).withColumn("window_start", date_format(col("window_start"), "HH:mm:ss")) \
 .withColumn("window_end", date_format(col("window_end"), "HH:mm:ss")) \
 .orderBy("server_id", "window_start")

# 8. Write the final output to a single CSV file
final_df.coalesce(1).write.csv("team_27_NET_DISK.csv", header=True, mode="overwrite")

print("\nSpark Job 2 finished. Output saved to team_27_NET_DISK.csv")
spark.stop()